  name: DynMapPE
  main: thebigsmileXD\DynMapPE\Main
  version: 0.0.1
  api: 1.0.0
  load: POSTWORLD
  prefix: "DynMapPE"
  authors: [thebigsmileXD]
  description: "DynMap portet to PocketMine"
  commands:
   dynmap:
    description: "Refresh the map data"
    usage: "/dynmap"
    permission: dynmap.cmd
  permissions:
    dynmap.cmd:
      description: Permission for all /dynmap commands.
      default: op